---
title: "Land cover model for WMAs in Alabama"
output: html_document
date: "2025-04-03"
---

Loading necessary libraries

```{r}
require(groundhog)
groundhog.library('sf', "2024-12-01")
groundhog.library('tigris', "2024-12-01")
groundhog.library('geodata', "2024-12-01")
groundhog.library('dplyr', "2024-12-01")
groundhog.library('colorspace', "2024-12-01")
groundhog.library('FedData', "2024-12-01")
groundhog.library("terra", "2024-12-01")
groundhog.library('randomForest', "2024-12-01")
# groundhog.library('terra', "2024-12-01")
groundhog.library('caret', "2024-12-01")
```



Loading fitted model

```{r}
# Download the file locally first
# download.file("https://github.com/ValenteLab/Sinka-study-files/raw/main/rf_model.RData", 
#               destfile = "rf_model.RData", mode = "wb")

# Now load the model
load("rf_model.RData")

# Check the object
print(rf_model)
```

Load stacked predictors

```{r}
# StackedPredictors = rast("/vsicurl/https://github.com/ValenteLab/Sinka-study-files/raw/refs/heads/main/StackedPredictors.tif")
StackedPredictors = rast("StackedPredictors.tif")
print(StackedPredictors)
```



Predictions

```{r}
# Generate predictions for the raster stack using the trained model
names(StackedPredictors)[names(StackedPredictors) == "2024Nlcd"] <- "X2024Nlcd"
map <- terra::predict(StackedPredictors, rf_model, type = "response")

# Plot the predicted land cover map
plot(map, main = "Predicted Land Cover Map")
```







